# Change these first
owner: clifff # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Shakedown Social
    url: https://shakedown.social
    maxResponseTime: 10000
  - name: Shakedown Social - Streaming
    url: https://shakedown.social/api/v1/streaming/health
    maxResponseTime: 10000
  - name: Shakedown Social - Files
    url: https://files.shakedown.social/accounts/avatars/109/357/389/718/265/462/original/dd80d2c95e48cfd2.jpeg
    maxResponseTime: 10000
status-website:
  theme: dark
  cname: status.shakedown.social
  # logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Status - Shakedown Social
  introTitle: "status.shakedown.social"
  introMessage: This page reports the uptime status of [Shakedown Social](https://shakedown.social).
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# https://upptime.js.org/docs/configuration
