# Change these first
owner: shakedown-social
repo: upptime # The name of this repository

sites:
  - name: Shakedown Social - Homepage
    url: https://shakedown.social
    maxResponseTime: 10000
  - name: Shakedown Social - Websockets
    url: https://shakedown.social/api/v1/streaming/health
    maxResponseTime: 10000
  - name: Shakedown Social - Uploads
    url: https://files.shakedown.social/accounts/avatars/109/357/389/718/265/462/original/dd80d2c95e48cfd2.jpeg
    maxResponseTime: 10000

status-website:
  theme: dark
  cname: status.shakedown.social
  # logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Status - Shakedown Social
  introTitle: "status.shakedown.social"
  introMessage: This page reports the uptime status of [Shakedown Social](https://shakedown.social). It is updated automatically every minute.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
assignees:
  - clifff

# custom schedule because we use a cloudflare worker to trigger
# the uptime workflow every minute. all other schedules are default
workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "0 0 * * *"
